version: '2'

services:
   db:
     image: mysql:5.6
     volumes:
       - db_data:/var/lib/mysql
       - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
     restart: always
     env_file: database.properties
     environment:
       MYSQL_DATABASE: kontalk
       MYSQL_USER: kontalk

   tigase:
     depends_on:
       - db
     image: kontalk/xmppserver
     ports:
       - "5222:5222"
       - "5269:5269"
     volumes:
       - ./data/privatekey.pem:/tmp/privatekey.pem
       - ./data/certificate.pem:/tmp/certificate.pem
       - ./data/cachain.pem:/tmp/cachain.pem
       - ./data/server-private.key:/tmp/server-private.key
       - ./data/server-public.key:/tmp/server-public.key
       - ./data/init.properties.in:/tmp/init.properties.in
       - ./data/trusted.pem:/home/kontalk/kontalk/tigase-kontalk/trusted.pem
     restart: always
     env_file: tigase.properties
     environment:
       MYSQL_DATABASE: kontalk
       MYSQL_USER: kontalk

volumes:
    db_data:
